# Generated by Django 3.1.2 on 2020-10-29 08:49

from django.db import migrations
from django.template.defaultfilters import slugify


def popular_slug(apps, schema_editor):
    Modulos = apps.get_model('modulos_aulas', 'ModuloAula')
    for modulo in Modulos.objects.all():
        modulo.slug = slugify(modulo.nome)
        modulo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modulos_aulas', '0002_moduloaula_slug'),
    ]

    operations = [
        migrations.RunPython(popular_slug)
    ]
