# Generated by Django 3.1.2 on 2020-10-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos_aulas', '0003_populando_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloaula',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
