# Generated by Django 3.1.2 on 2020-10-30 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos_aulas', '0004_slug_uniq_não_nulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('nome', models.CharField(max_length=32)),
                ('descricao', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('v_id', models.CharField(max_length=32)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulos_aulas.moduloaula')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
