# Generated by Django 3.1.3 on 2020-11-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos_artigos', '0002_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloartigo',
            name='nome',
            field=models.CharField(max_length=300),
        ),
    ]
